.\" sipwitchqt-desktop - run desktop client instance
.\" Copyright (C) 2018 Tycho Softworks
.\"
.\" This manual page is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc.,59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.\"
.\" This manual page is written especially for Debian GNU/Linux.
.\"
.TH sipwitchqt-desktop "1" "June 2018" "SipWitchQt" "Tycho Softworks"
.SH NAME
sipwitchqt-desktop \- run desktop client instance 
.SH SYNOPSIS
.B sipwitchqt-desktop
.RI [ options ]
.br
.SH DESCRIPTION
This starts the desktop client ui.  This will connect with a sipwitchqt server.
It can also be started minimized at user login, and operate thru a tray or dock
icon.
.SH OPTIONS
.TP
.B \-\-minimize
Minimize to system tray at startup.
.TP
.B \-\-notray
Display system tray entirely.
.TP
.B \-\-reset
Reset config file to system defaults during startup.
.SH AUTHOR
.B sipwitchqt-desktop
was written by David Sugar <tychosoft@gmail.com>.
.SH "REPORTING BUGS"
Report bugs to tychosoft@gmail.com.
.SH COPYRIGHT
Copyright \(co 2018 Tycho Softworks.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.

