stages:
- build
- docs


build:
  image: in1t3r/gitlabqt:latest
  stage: build
  script:
    - qmake
    - make
  when: on_success
  tags:
    - docker
  only:
    - master

docs:
  image: in1t3r/gitlabqt:documentation
  stage: docs
  script:
    - qmake && make docs
  when: manual
  tags:
    - docker
  only:
    - master
  artifacts:
    expire_in: 1 week
    paths:
      - doc/
  allow_failure: false
  