stages:
#- build
- test
- docs

#We do not have need anymore for the build stage
#build:
#  image: in1t3r/gitlabqt:build
#  stage: build
#  script:
#    - qmake
#    - make
#  when: on_success
#  tags:
#    - docker
#  only:
#    - master
    
    
#tests every commit including merge requests    
test:
  image: in1t3r/gitlabqt:build
  stage: test
  script:
    - qmake
    - make
  tags:
    - docker

  artifacts:
    expire_in: 1 month
    when: on_failure
    paths:
      - ./*.log
      - Common/*.log
      - Main/*.log
      - Database/*.log
      - Stack/*.log
      - testdata/*.log

    

docs:
  image: in1t3r/gitlabqt:documentation
  stage: docs
  script:
    - qmake
    - make docs
  when: manual
  tags:
    - docker
  only:
    - master
  artifacts:
    expire_in: 1 week
    paths:
      - doc/
  allow_failure: false
  
