stages:
#- build
- test
- docs

#We do not have need anymore for the build stage
#build:
#  image: in1t3r/gitlabqt:build
#  stage: build
#  script:
#    - qmake
#    - make
#  when: on_success
#  tags:
#    - docker
#  only:
#    - master
    
    
#tests every commit including merge requests    
test:
  image: in1t3r/gitlabqt:build
  stage: test
  script:
    - qmake | tee qmake.log
    - make | tee make.log
  tags:
    - docker

  artifacts:
    expire_in: 2 weeks
    when: always
    paths:
      - *.log
    

    

docs:
  image: in1t3r/gitlabqt:documentation
  stage: docs
  script:
    - qmake
    - make docs
  when: manual
  tags:
    - docker
  only:
    - master
  artifacts:
    expire_in: 1 week
    paths:
      - doc/
  allow_failure: false
  
