.\" ipl-sipwtch - generate initial mysql database for sipwitch servers
.\" Copyright (C) 2018 Tycho Softworks
.\"
.\" This manual page is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc.,59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.\"
.\" This manual page is written especially for Debian GNU/Linux.
.\"
.TH ipl-sipwitch "1" "January 2018" "SipWitchQt" "Tycho Softworks"
.SH NAME
ipl-sipwitch \- generate initial mysql database for sipwitch servers
.SH SYNOPSIS
.B ipl-sipwitch
.br
.SH DESCRIPTION
This utility is used to create and initially populate a mysql database with
initial authorization records when deploying a new sipwitch instance.  The
values needed to create a new database, including initial passwords, are
prompted for on the command line. The connection information for the mysql
server is typically read from the servers /etc/sipwitchqt.conf file.  Since the
utilities can be installed stand-alone on a separate machine, you can instead 
create a local config file with database connection info using the -c path option.
.SH AUTHOR
.B ipl-sipwitch
was written by David Sugar <tychosoft@gmail.com>.
.SH "REPORTING BUGS"
Report bugs to tychosoft@gmail.com.
.SH COPYRIGHT
Copyright \(co 2018 Tycho Softworks.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.

