.\" swlite-authorize - manage sipwitchqt user authorizations in sqlite backend
.\" Copyright (c) 2017 Tycho Softworks
.\"
.\" This manual page is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc.,59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.\"
.\" This manual page is written especially for Debian GNU/Linux.
.\"
.TH swlite-authorize "1" "December 2017" "SipWitchQt" "Tycho Softworks"
.SH NAME
swlite-authorize \- manage sipwitchqt user authorizations in sqlite backend
.SH SYNOPSIS
.B swlite-authorize
.RI [ options ]
.I user
.br
.B swlite-authorize
.br
.SH DESCRIPTION
The purpose of swlite-authorize is to manage authorization group records for a backend 
sqlite sipwitchqt database.  This includes both creating and removing (or suspending)
authorized users, and also setting the SIP digest password.

If used with no options the current authorization realm is shown.  If a userid is given
then the password to use will be prompted on the console.  Otherwise optios can be
used to set digest mode, and whether to suspend or drop a user.
.SH OPTIONS
.TP
.B \-\-sha256
Use a SHA-256 digest when setting a password (default is MD5).
.TP
.B \-\-sha512
Use a SHA-512 digest when setting a password (default is MD5).
.TP
.B \-\-create
Create (add) the authorization if it does not exist.
.TP
.B \-\-drop
Drop (remove) the authorized user and associated extension record.  Any active calls or
registrations should also be terminated.
.TP
.B \-\-local
Local device group authorization.
.TP
.BI \-\-password value
Force setting of password.  Useful for script driven db setup.
.TP
.B \-\-remote
Remote accessible user authorization.
.TP
.B \-\-suspend
Suspend the users account.  Any active calls and registrations should also be cancelled.
.TP
.B \-\-team
Team group authorization.
.SH AUTHOR
.B swlite-authorize
was written by David Sugar <tychosoft@gmail.com>.
.SH "REPORTING BUGS"
Report bugs to tychosoft@gmail.com.
.SH COPYRIGHT
Copyright \(co 2017 Tycho Softworks.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.

