.\" swlite-initialize - create an admin authorization and extension in sqlite backend
.\" Copyright (C) 2017-2018 Tycho Softworks
.\"
.\" This manual page is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc.,59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.\"
.\" This manual page is written especially for Debian GNU/Linux.
.\"
.TH swlite-initialize "1" "December 2017" "SipWitchQt" "Tycho Softworks"
.SH NAME
swlite-initialize \- create an admin authorization and extension in sqlite backend
.SH SYNOPSIS
.B swlite-initialize
.SH DESCRIPTION
The purpose of swlite-initialize is to take a newly created and empty sqlite
database, such as the one created by default by the server when installed from
a package, and add a user authorization that has full administration access.
Using this initial user all other admin tasks, including creating additional
users, can then be performed from the desktop client.

If you are using mysql then you would use the ipl-sipwitch utility instead.
.SH OPTIONS
.TP
.B \-\-sha256
Use a SHA-256 digest when setting a password (default is MD5).
.TP
.B \-\-sha512
Use a SHA-512 digest when setting a password (default is MD5).
.SH AUTHOR
.B swlite-initialize
was written by David Sugar <tychosoft@gmail.com>.
.SH "REPORTING BUGS"
Report bugs to tychosoft@gmail.com.
.SH COPYRIGHT
Copyright \(co 2017 Tycho Softworks.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.

